### ISSUE TITLE
Integrate onetrust cookie conset sdk

### ISSUE THREAD

**Issue by mhaack** [Netcentric/cn-website#12]

**Comment by verlok-cn** [comment]
To whom is going to work on this:

Please update the value of the data attribute on the page `[data-wp-page-cookie]` upon users make their choice.

**Comment by NCalexiaeche** [comment]
Hi @verlok-cn isn't it solved? if nor should we open a bug or enhancement ticket for this particular attribute instead?

**Comment by verlok-cn** [comment]
Hey @NCalexiaeche, I see the layer of cookie acceptance on the home of NC-biz, so I guess this has been worked.

However, since #72 has been closed, we need to make sure that when users make a choice by clicking on the cookie layer, the `data-wp-page-cookie` is updated via JavaScript.

I will create a new ticket so we can close this.
