### ISSUE TITLE
Blog redirects on CDN

### ISSUE THREAD

**Issue by nc-andreashaller** [Netcentric/cn-website#214]
Currently the redirects listed in https://docs.google.com/spreadsheets/d/18gso0z0wR9-ZE1oH4RK9wTmEAXcNUhImsk0ouzdUngY/edit#gid=0 do not work because we are redirecting on CDN level already from for example /insights/2014.html to /insights/2014 which then hits a 404 and redirects to /. Also having those redirects added manually would mean to add a line every month which is not really user friendly.

What we need to do: remove all redirects from the sheet and add a generic redirect rule to the CDN redirecting URLs in the form /insights/2014 to /insights. The same should be done for /**de**/insights/xxxx/xx.

**Comment by EduNCgit** [comment]
I checked both links for redirects. https://www.netcentric.biz/offices will redirect to **/how-we-work/studios**
But the german version **de/offices** will not redirect and will just show https://www.netcentric.biz/de/offices

**Comment by jonatan-lledo-netcentric** [comment]
I checked also the same 2 links to redirect to studios and it works for me in incognito mode and in my firefox, and it redirects as expected in both links. But, in /de/how-we-work page has an old link to the offices https://www.netcentric.biz/content/netcentric/global/de/how-we-work/studios, and I test to add a rule to redirect also to the studio page and it doesn't work. I don't know if is because it goes to the same page as the other link, or because the redirections don't work as expected

**Comment by nc-andreashaller** [comment]
Fixed and waiting with #180
