### ISSUE TITLE
CDN Setup

### ISSUE THREAD

**Issue by nc-andreashaller** [Netcentric/cn-website#26]
For the CDN setup we should follow https://www.hlx.live/docs/byo-cdn-fastly-setup, assuming we continue on Fastly. 

As we decided to **not** migrate the german part of the page we need to implement a filter on CDN level to forward certain paths to AEM:

- /de*
- /etc.clientlibs/*
- /content/experience-fragments/netcentric/global/de/*
- /content/dam/*

**Comment by rofe** [comment]
You may also consider adding a VCL snippet which does a generic redirect from `/foo.html` to `/foo` to make sure links from the old site will be redirected to their extensionless counterparts on the new site.

**Comment by sbeckernc** [comment]
seems insufficient as there are 2 resources still loaded with a .html extension
footer.plain.html and nav.plain.html . These are now excluded from the matches as well and it is now functional on stage

instead of redirecting I have rewritten in fastly to without .html  .

Even though the browser initially shows the .html the backend will see it without .html and upon a further nav bar link click it will disappear. 

Optimally the .html is dropped from the EN language selector when on the DE page when still on the current AEM implementation.

**Comment by mhaack** [comment]
@sbeckernc , @nc-andreashaller instead of footer.plain.html and nav.plain.html can we match to `*.plain.html ` as we might have more of these URL patterns.

**Comment by sbeckernc** [comment]
done also changed to a 301. config is deployed to staging and ready for prod.
