### ISSUE TITLE
Block 4 - Expanding cards 

### ISSUE THREAD

**Issue by DaphneKoren** [Netcentric/cn-website#328]
**User story:**
As a user I would like to be able to Expanding cards so that I can display content in an interactive way

This block is created to provide a replacement for the ION component seen in [/diversity-testimonials](https://expertise.netcentric.biz/diversity-testimonials)

**AC:**

- Each card has an Image, Title +pre-title and text 
- Cards expanding automatically 
- Time to expand of 700 milliSeconds 
- Autoplay delay 5 seconds
- Navigation dots at the bottom 
- Cards expand on click as well
- The background colour of each card is different and follows the Rainbow colour scheme
- Max number of cards 3
- Min number of cards 2
- Text allows lists, Bold/underline/cursive design
- Text, Title and Pre-title length is decided by the space provided in smallest viewport
- Before card is expanded only a pre title and title are shown with a 'Rainbow' background colour
- When the item is in focus the section expands with animation
- When a card is active by animation or clicked, Image,  Title Pre-title and Content are all visible 

**Specs:**
[Block 4 -Expanding cards](https://projects.netcentric.biz/wiki/display/NCWEB/Block+4+-Expanding+cards?src=contextnavpagetreemode)
[Accessibility colour recommendation](https://projects.netcentric.biz/wiki/display/NCWEB/Accessibility+colour+recommendation?src=contextnavpagetreemode)

More info:
Ion component in use can be seen here 
https://main--cn-website--netcentric.hlx.page/careers/diversity-inclusion

**Comment by alexnerdrumhansen** [comment]
Tested with https://328-expanding-cards--cn-website--netcentric.hlx.page/drafts/mburicea/careers/expading-cards which shows we have a bug.
The text bleeds into the image currently. We should try to limit the width of the text field so that doesn't happen.
<img width="1245" alt="Screenshot 2023-07-25 at 12 46 33" src="https://github.com/Netcentric/cn-website/assets/131788856/8cc45673-1168-44b7-9cfa-9d55039a739a">
<img width="1217" alt="Screenshot 2023-07-25 at 12 46 39" src="https://github.com/Netcentric/cn-website/assets/131788856/f68063a7-ef49-4d19-b836-bf6c4b78fd7a">
<img width="1236" alt="Screenshot 2023-07-25 at 12 46 43" src="https://github.com/Netcentric/cn-website/assets/131788856/91b1e8f7-2d5c-4217-a15c-7e23a3e4ef7e">

**Comment by alexnerdrumhansen** [comment]
Thanks @mihai-buricea-net!
Verified as fixed.
