### ISSUE TITLE
DE: Links within Experience Operations redirect to Homepage

### ISSUE THREAD

**Issue by alexnerdrumhansen** [Netcentric/cn-website#352]
Go to https://www.netcentric.biz/de/what-we-do/experience-operations
Click on the links marked in the image below:

<img width="1292" alt="Screenshot 2023-06-16 at 09 19 23" src="https://github.com/Netcentric/cn-website/assets/131788856/bb93b6c6-28f6-42a9-b181-f6fc90a9b3cd">
All these links redirect to the Homepage (in German at least).

**Comment by NCalexiaeche** [comment]
What is the issue here @alexnerdrumhansen , can we fix the content issue directly?

**Comment by Gonzalo-CG** [comment]
Currently, the 2 links marked in red redirect to a 404 on prod, but work fine on preview. I'd assume this is because those 2 pages have not been published yet. 
The pages referred to in those 2 links are currently in English, will confirm with marketing later today if they should instead be in German or not.

**Comment by alexnerdrumhansen** [comment]
Verified as fixed.
