### ISSUE TITLE
Create GitHub Action to insert annotations in LiveUX via Annotations API on deployments to production

### ISSUE THREAD

**Issue by verlok** [Netcentric/cn-website#45]
As a web performance consultant using LiveUX, I need to know when something changed on the website, so that I can easily find a cause of an improvement or regression, and I can know that once ther is a GitHub Action sending an annotation to LiveUX.

So the ask is to create a GitHub Action that calls [the LiveUX annotations API](https://projects.netcentric.biz/wiki/display/LUX/Annotations+API) to insert a new annotation on deployments to production environments.

Please reach out to me (Andrea Verlicchi) if you need more information.

**Comment by nc-andreashaller** [comment]
As there is no dedicated pipeline for a go live but everything merged to `main` is automatically live we should have the action triggered by changes to the `main` branch.

@verlok obviously this only includes code changes but no content changes which might also affect performance.

**Comment by verlok-cn** [comment]
That's correct, @nc-andreashaller.

For content changes, we would need other annotations sent from a sidekick extension (Lars suggested it [here](https://ncchat.slack.com/archives/C03K480JSF4/p1670318929676429?thread_ts=1670309891.727229&cid=C03K480JSF4)), but that would be another ticket.

I opened the issue with the wrong user, but please tag @verlok-cn for work related work.

@NCalexiaeche was this ticket assigned to me because I needed to confirm?

**Comment by nc-andreashaller** [comment]
In the meantime there is a server-side event triggered for content changes we can hook into. We used it successfully for search already.

**Comment by nc-andreashaller** [comment]
@verlok-cn could you share which index name we need to use?

**Comment by nc-andreashaller** [comment]
Job is created and works as soon as I get my hands on a valid API key: https://ncchat.slack.com/archives/C02J4CACE3C/p1676009769015699?thread_ts=1675786902.131849&cid=C02J4CACE3C

**Comment by nc-andreashaller** [comment]
Done and tested, works.
